import Foundation

enum LocalizationCatalogReferences {
    // Xcode's localization validator does not detect keys routed through the custom L10n wrapper.
    // Keep static literal references here so the string catalog remains associated with source code.
    static let resources: [LocalizedStringResource] = [
        "add_item.add_title",
        "add_item.attach_document",
        "add_item.camera",
        "add_item.edit_title",
        "add_item.library",
        "add_item.section.details",
        "anthropic.error.missing_api_key",
        "app.name",
        "auth.debug.handling_reset_link",
        "auth.debug.ignored_link",
        "auth.debug.received_link",
        "auth.debug.recovery_link_received",
        "auth.debug.recovery_session_established",
        "auth.debug.reset_link_failed",
        "auth.create_account",
        "auth.email",
        "auth.error.enter_and_confirm_password",
        "auth.error.enter_email_for_reset",
        "auth.error.empty_credentials",
        "auth.error.http_status",
        "auth.error.minimum_new_password",
        "auth.error.network_request_failed",
        "auth.error.passwords_do_not_match",
        "auth.error.reset_link_missing_info",
        "auth.error.unknown_http",
        "auth.info.confirm_email",
        "auth.info.password_reset_sent",
        "auth.password",
        "auth.sign_in",
        "auth.subtitle",
        "auth.toggle.sign_in",
        "auth.toggle.sign_up",
        "biometric.button.face_id",
        "biometric.button.touch_id",
        "biometric.error.failed",
        "biometric.error.unavailable",
        "biometric.prompt.default",
        "biometric.prompt.face_id",
        "biometric.prompt.touch_id",
        "camera.open_settings",
        "camera.permission_message",
        "camera.permission_required",
        "category.art",
        "category.art_decor_documents",
        "category.artwork",
        "category.bags_luggage",
        "category.bbq_grill",
        "category.beds_mattresses_wardrobes",
        "category.bicycles",
        "category.books",
        "category.cash",
        "category.cleaning_equipment",
        "category.clothing",
        "category.clothing_personal_items",
        "category.collectibles",
        "category.decor_items",
        "category.designer_bags",
        "category.desks_office_chairs",
        "category.dining_tables_chairs",
        "category.electronics_appliances",
        "category.electronics",
        "category.food_storage",
        "category.furniture_household_fixtures",
        "category.furniture",
        "category.gaming_consoles",
        "category.garden_furniture",
        "category.hobby_equipment",
        "category.important_documents",
        "category.jewelry",
        "category.jewellery",
        "category.kitchen_appliances",
        "category.kitchenware_household_goods",
        "category.lamps_lighting",
        "category.laptops_desktops_tablets",
        "category.miscellaneous",
        "category.musical_instruments",
        "category.office_supplies",
        "category.other",
        "category.outdoor_items",
        "category.personal_valuables",
        "category.plates_glasses_cutlery",
        "category.pots_pans_utensils",
        "category.routers_networking_equipment",
        "category.shelving_storage_units",
        "category.shoes_outerwear",
        "category.small_appliances",
        "category.smartphones_smartwatches",
        "category.sofas_armchairs",
        "category.sports_equipment",
        "category.tools_equipment",
        "category.toys",
        "category.tvs_media_systems",
        "category.washing_machine_dryer",
        "category.watches",
        "common.add",
        "common.cancel",
        "common.done",
        "common.edit",
        "common.ok",
        "common.placeholder_dash",
        "common.save",
        "config.error.load_failed",
        "item.field.category",
        "item.field.currency",
        "item.field.declared_value",
        "item.field.name",
        "item.field.notes",
        "item.field.purchase_price",
        "item.field.serial_number",
        "item.field.year",
        "item.field.year_purchased",
        "item_detail.ai_estimate_uppercase",
        "item_detail.declared_value_uppercase",
        "item_detail.documents",
        "item_detail.documents_uppercase",
        "item_detail.estimate_coming",
        "item_detail.estimate_error",
        "item_detail.export_pdf",
        "item_detail.no_documents_attached",
        "item_detail.no_photos_attached",
        "item_detail.no_photos_yet",
        "item_detail.photos",
        "item_detail.photos_uppercase",
        "item_detail.upload_error",
        "language.danish",
        "language.english",
        "%lld photos",
        "%lld photos • %lld docs",
        "Access removed for %@.",
        "Accept invite",
        "Add evidence to estimate value",
        "Accepted",
        "Add object",
        "Add photo",
        "Add photos first. Documents can be attached before saving.",
        "Add the first object to start documenting ownership.",
        "AI assisted",
        "Analyzing evidence",
        "Back",
        "Back to sign in",
        "Capture or upload",
        "Capture or upload the files that prove ownership.",
        "Category",
        "Cancel",
        "Check the summary before saving to your vault.",
        "Choose a new password for your account.",
        "Confidence",
        "Confirm password",
        "Confirm the essential facts for retrieval and claims.",
        "Conservative estimate based on available evidence.",
        "Continue",
        "Continue your password reset in VaultDoc.",
        "Create a secure home for your records.",
        "Delete",
        "Details",
        "Documents",
        "Encrypted",
        "Essential details",
        "Estimated value",
        "Evidence",
        "Higher",
        "Images and documents supporting ownership.",
        "Incomplete",
        "Invite sent to %@.",
        "Low",
        "Main category",
        "Make sure the record is clear enough to retrieve quickly later.",
        "Manual review",
        "Metadata",
        "Missing evidence",
        "Moderate",
        "New password",
        "No matching items",
        "No new documents attached.",
        "Object",
        "Object name",
        "Offline",
        "openai.error.api_status",
        "openai.error.invalid_response",
        "openai.error.missing_api_key",
        "Only record what helps identification and value.",
        "Overview",
        "Pending",
        "Photos",
        "Proof of ownership and recovery-ready records.",
        "Receipts, certificates, and manuals improve proof quality.",
        "Refresh estimate",
        "Request a secure password reset link.",
        "Review",
        "Secure access",
        "Select category",
        "Signals",
        "Sign in to your secure document vault.",
        "Status",
        "Step %lld",
        "Syncing",
        "The details that matter in urgent situations.",
        "Try a different search term.",
        "Unnamed",
        "Use at least %lld characters.",
        "Valuation",
        "Verified",
        "Your password reset link has opened in VaultDoc.",
        "Your recovery session is complete.",
        "Your records are stored securely and ready when needed.",
        "You are now sharing the family inventory.",
        "pdf.footer.generated_by",
        "pdf.footer.page",
        "privacy.ai_estimates",
        "privacy.ai_estimates_body",
        "privacy.camera_photos",
        "privacy.camera_photos_body",
        "privacy.contact",
        "privacy.contact_body",
        "privacy.data_storage",
        "privacy.data_storage_body",
        "settings.about",
        "settings.account",
        "settings.active_categories_count",
        "settings.active_currencies_count",
        "settings.app_language",
        "settings.build",
        "settings.default_currency",
        "settings.export",
        "settings.export_all_items_pdf",
        "settings.language",
        "settings.privacy_policy",
        "settings.sign_out",
        "settings.signed_in_as",
        "settings.title",
        "settings.version",
        "Family member email",
        "Forgot password?",
        "Invited family members can add items to the same inventory after they accept the invite.",
        "Invited you to join a shared family inventory.",
        "Preparing your vault",
        "Secure records for the moments that matter.",
        "Send family invite",
        "Send reset link",
        "Shared Inventory",
        "Stored securely",
        "Tap continue to verify your recovery link and open the password change screen.",
        "Update password",
        "Your inventory is currently private.",
        "Your password has been updated.",
        "supabase.data.delete_failed",
        "supabase.data.download_failed",
        "supabase.data.empty_response",
        "supabase.data.not_authenticated",
        "supabase.data.server_error",
        "supabase.data.upload_failed",
        "supabase.error.missing_configuration",
        "supabase.reset_link.invalid",
        "supabase.reset_link.invalid_type",
        "valuation.error.api_request_failed",
        "valuation.error.missing_photos",
        "valuation.error.parse_failed",
        "valuation.error.unsupported_image_format",
        "valuation.error.unsupported_subject",
        "vault.add_first_item",
        "vault.delete_error",
        "vault.empty_message",
        "vault.empty_title",
        "vault.search_prompt",
        "vault.stat.documented",
        "vault.stat.items",
        "vault.stat.total_value",
        "•",
        "vault.title"
    ]
}
